# Generated by Django 5.0.3 on 2024-05-15 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimagesmodel',
            name='image',
        ),
    ]
