# Generated by Django 5.0.3 on 2024-05-15 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_galleryimagesmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimagesmodel',
            name='image',
            field=models.ImageField(upload_to='gallery'),
        ),
        migrations.CreateModel(
            name='PaintingForSaleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='painting_for_sale')),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('cost', models.CharField(max_length=10)),
                ('reviews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.reviewmodel')),
            ],
        ),
    ]
