# Generated by Django 5.0.3 on 2024-05-15 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_galleryimagesmodel_image_paintingforsalemodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paintingforsalemodel',
            name='reviews',
        ),
        migrations.CreateModel(
            name='PaintingReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comments', models.TextField()),
                ('painting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.paintingforsalemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ReviewModel',
        ),
    ]
