# Generated by Django 5.0.3 on 2024-05-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_remove_paintingforsalemodel_reviews_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paintingforsalemodel',
            name='description',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paintingforsalemodel',
            name='title',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
