# Generated by Django 5.0.3 on 2024-05-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_paintingforsalemodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paintingforsalemodel',
            name='type',
            field=models.CharField(choices=[('acrylic', 'Acrylic Painting'), ('oil', 'Oil Painting'), ('watercolour', 'Water Colour Painting'), ('pencilcolour', 'Pencil Colour Painting'), ('charcoal', 'Charcoal Painting'), ('pencilpotrait', 'Pencil Potrait')], default='acrylic', max_length=20),
        ),
    ]
