# Generated by Django 5.0.3 on 2024-05-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressmodel',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='state',
            field=models.CharField(max_length=20),
        ),
    ]
