# Generated by Django 5.0.3 on 2024-06-12 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
